epam/edp-tekton

.github/workflows/pr.yaml

chore: Align commit message pattern (#160)

---

charts/pipelines-library/README.md
charts/pipelines-library/values.yaml

- [+] Bug fix (non-breaking change which fixes an issue)
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] My changes generate no new warnings
- [+] Pull Request contain one commit. I squash my commits.

chore: Adjust tekton pruner logic

---

charts/tekton-cache/templates/deployment.yaml

We need to use recreate strategy since cache need to use volume.
Fixes # (171)

chore: Switch cache to recreate strategy type

---

charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml

fix: Set full stage name in autotests tekton task

---

charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/github-build-default.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/github-review.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/fastapi/gitlab-review.yaml

fix: Resolve Version Conflict Between h11 and httpcore

---

.github/workflows/codeql.yaml

Update CodeQL to the latest version

chore: Update CodeQL to the latest version (#203)

---

charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-general.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml

chore: Set default branch during project creation

---

charts/pipelines-library/README.md
charts/pipelines-library/scripts/tekton-prune.sh
charts/pipelines-library/templates/resources/pruner/configmap.yaml
charts/pipelines-library/templates/resources/pruner/cron-job.yaml
charts/pipelines-library/templates/resources/pruner/rbac.yaml
charts/pipelines-library/values.yaml

chore: Update tekton pruner logic

---

charts/pipelines-library/templates/resources/pruner/configmap.yaml

chore: Align argo diff for pruner

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/custom-pipelines/Chart.lock
charts/custom-pipelines/Chart.yaml
charts/custom-pipelines/README.md
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/tekton-cache/Chart.yaml
charts/tekton-cache/README.md

Jira: EPMDEDP-13912
Fixes #211

chore: Update current version

---

.github/workflows/e2e.yaml
hack/install-kuttl.sh
hack/kind-1.27.yaml
hack/kind-1.28.yaml
hack/kind-1.29.yaml
kuttl-test.yaml

chore: Update kuttle and kind images (#215)

---

.github/workflows/pr.yaml
charts/custom-pipelines/templates/tasks/HelmPushGhPages.yaml
charts/custom-pipelines/templates/tasks/e2e.yaml
charts/custom-pipelines/templates/tasks/integration-tests-keycloak.yaml
charts/custom-pipelines/templates/tasks/integration-tests-nexus.yaml
charts/custom-pipelines/templates/tasks/release/HelmPushGhRelease.yaml
charts/custom-pipelines/templates/tasks/waitFor.yaml
kuttl-test.yaml

- Update tekton-helm image
- Fix CI for PR

chore: Update tekton-helm image version (#215)

---

charts/pipelines-library/templates/resources/gitservers/eventlistener.yaml
charts/pipelines-library/templates/resources/gitservers/ingress-eventlistener.yaml
charts/pipelines-library/templates/resources/route-eventlistener.yaml
charts/pipelines-library/tests/test_baseline.py
charts/pipelines-library/tests/test_github_integration.py
tests/e2e/gerrit/02-assert.yaml
tests/e2e/github/02-assert.yaml
tests/e2e/gitlab/02-assert.yaml

- Update the name of the gitservers eventlistener by removing 'edp' prefix.
- Add the 'app.edp.epam.com/gitServer' label with the name of GitServer.
Fixes #222 

chore: Update gitservers event listener name and add label (#222)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/resources/grafana/dashboards/grafana-dashboard-tekton.yaml
charts/pipelines-library/templates/resources/grafana/service-monitor.yaml
charts/pipelines-library/values.yaml

**# Pull Request
Add Grafana Tekton dashboard and update kube-prometheus-stack chart version
Fixes #227 
Add any other context or screenshots about the feature request here.**

chore: Add Grafana Tekton dashboard (#227)

---

charts/pipelines-library/templates/tasks/commit-validate.yaml

fix: Fix commit-validate task to check only the first line

---

charts/pipelines-library/templates/pipelines/_common_python.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gerrit-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/ansible/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/ansible/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/ansible/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/ansible/gitlab-review-lib.yaml
charts/pipelines-library/templates/tasks/ansible.yaml
charts/pipelines-library/tests/test_python_pipelines.py

Description
This commit introduces new CI/CD pipeline configurations and tasks, along with corresponding tests for the Ansible codebase. These additions are aimed to improve automation practices and ensure better quality control of Ansible-related procedures.
Fixes #236
Type of change
The added pipelines and tasks have been tested within a controlled CI environment to ensure they execute as expected. The tests include running ansible-lint checks, executing ansible playbooks in test mode, and verifying the output. Additionally, the integration with version control systems (Git providers) like GitHub, GitLab, and Gerrit has been validated to ensure the pipelines trigger appropriate actions upon code pushes and pull requests.
Checklist:

feat: Add pipelines tasks tests for new codebase ansible(#236)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/triggers/github/trigger-review.yaml
charts/pipelines-library/values.yaml

feat: Add GitHub owners check configuration

---

charts/pipelines-library/templates/tasks/kaniko-dockerbuild-verify.yaml

Fix code duplicate in charts/pipelines-library/templates/tasks/kaniko-dockerbuild-verify.yaml
Fixes # (#242)
Pass Helm lint.

fix: Fix code duplication in dockerbuild-verify Task

---

charts/pipelines-library/templates/pipelines/cd/clean.yaml
charts/pipelines-library/templates/tasks/cd/clean.yaml
charts/pipelines-library/templates/triggers/cd/clean.yaml

feat: Add clean pipelines for tekton

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
charts/pipelines-library/tests/test_gerrit_integration.py
charts/pipelines-library/values.yaml

chore: Update Gerrit Trigger Template for Remote Cluster Deployment

---

.github/workflows/release.yaml
README.md

Renamed the EDP name matches to KubeRocketCI.
Fixes #258

chore: Update KubeRocketCI names (#258)

---

charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml

fix: Update parameter definition 

---

charts/pipelines-library/templates/pipelines/_common_c.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/с/cmake/github-build-default.yaml
charts/pipelines-library/templates/pipelines/с/cmake/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/cmake/github-review.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/cmake/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/с/make/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/с/make/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/make/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/с/make/github-build-default.yaml
charts/pipelines-library/templates/pipelines/с/make/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/make/github-review.yaml
charts/pipelines-library/templates/pipelines/с/make/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/с/make/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/с/make/gitlab-review.yaml
charts/pipelines-library/templates/tasks/edp-c.yaml

feat: Add C make/cmake application pipelines

---

charts/pipelines-library/templates/pipelines/rpm/github-build-default.yaml
charts/pipelines-library/templates/pipelines/rpm/github-build-edp.yaml
charts/pipelines-library/templates/tasks/edp-rpm.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/GetVersion.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/GetVersionEDP.yaml

feat: Implement rpm build functionality

---

charts/pipelines-library/templates/tasks/edp-rpm.yaml

fix: Align rpm-build argo diff

---

README.md

This minor change replaces EDP with KubeRocketCI in the note in the README.md file.

docs: Replace EDP with KubeRocketCI in README md (#268)

---

charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml

The goal of this task is to integrate an existing custom task, specifically an `ApprovalTask`, from the [KubeRocketCI Tekton Custom Task repository](https://github.com/KubeRocketCI/tekton-custom-task) into our existing Tekton pipeline. This addition aims to introduce a manual approval step within the CI/CD process, enhancing control and flexibility over deployment phases.
Deployed on the self environment.

feat: Add deploy pipeline with approve task(#279)

---

CHANGELOG.md
charts/common-library/templates/_common_gitlab.yaml
charts/pipelines-library/templates/pipelines/docker/kaniko/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/opa/gitlab-review-lib.yaml

chore: Update report message

---

charts/pipelines-library/templates/pipelines/java/maven/github-rpm-build-default.yaml
charts/pipelines-library/templates/pipelines/java/maven/github-rpm-build-edp.yaml

We have properly set env variables so no params are required for make

chore: Do not set make parameters for rpm build (#282)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/dashboard/role.yaml
charts/pipelines-library/values.yaml

Updated Tekton-dashboard version to v0.50.0.
Fixes #285

chore: Update Tekton-dashboard version to v0.50.0 (#286)

---

.github/workflows/e2e.yaml
.github/workflows/pr.yaml
.github/workflows/release.yaml
hack/install-kuttl.sh
hack/kind-1.30.yaml

Adding tests for Kubernetes 1.30 and updating Kubectl to the latest stable version.
Relates issue #282 
I have tested the changes by running the existing test suite against Kubernetes 1.30 and the latest version of Kubectl. Additionally, I have added new tests specifically for these versions.
N/A
N/A

chore: Add k8s 1.30 check and update kuttle (#282)

---

charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-build-default.yaml
hack/validate_tekton.py

Validate the structure of Tekton Task and Pipeline
Related Issue #290

chore: Add check for the Tekton Pipeline and Task structure (#290)

---

charts/pipelines-library/templates/tasks/get-cache.yaml
charts/pipelines-library/templates/tasks/save-cache.yaml

Switch cache compression algorithm from gzip to zstd.
Fixes #294

chore: Switch cache compression algorithm to zstd (#294)

---

charts/pipelines-library/templates/tasks/get-cache.yaml
charts/pipelines-library/templates/tasks/save-cache.yaml

Updated version of base images.
Fixes #289

chore: Update base image for cache tasks (#294)

---

charts/pipelines-library/templates/tasks/get-cache.yaml
charts/pipelines-library/templates/tasks/save-cache.yaml

Update save-cache and get-cache tasks code.
Fixes #289

chore: Update save-cache and get-cache tasks (#294)

---

charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml

Add description to the approval step of promotion procedure

chore: Add description to the approval promote procedure (#279)

---

hack/validate_tekton.py

chore: Align tasks field in test (#290)

---

charts/pipelines-library/templates/pipelines/_common_c.yaml
charts/pipelines-library/templates/pipelines/_common_docker.yaml
charts/pipelines-library/templates/pipelines/_common_dotnet.yaml
charts/pipelines-library/templates/pipelines/_common_go.yaml
charts/pipelines-library/templates/pipelines/_common_java_gradle.yaml
charts/pipelines-library/templates/pipelines/_common_java_maven.yaml
charts/pipelines-library/templates/pipelines/_common_js_npm.yaml
charts/pipelines-library/templates/pipelines/_common_python.yaml
charts/pipelines-library/templates/tasks/kaniko.yaml

Removed Kaniko cache usage for build pipelines
Fixes #309

chore: Remove kaniko cache usage (#309)

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_bitbucket.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/tasks/bitbucket-set-status.yaml

feat: Add bitbucket-set-status task for tekton pipelines

---

README.md
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/README.md.gotmpl
charts/pipelines-library/templates/_helpers.tpl
charts/pipelines-library/values.yaml

Added support for BitBucket as GitServer 
Fixes #317

feat: Add Support for BitBucket as GitServer (#317)

---

cmd/interceptor/main.go
go.mod
go.sum
pkg/event_processor/bitbucket/bitbucket.go
pkg/event_processor/bitbucket/bitbucket_test.go
pkg/event_processor/codebase.go
pkg/event_processor/event.go
pkg/event_processor/github/github.go
pkg/event_processor/github/github_test.go
pkg/interceptor/edp_interceptor.go

Add the last commit message to the interceptor response for BitBucket Cloud.
Fixes #311 
- Unit test
- Manual local testing

feat: Add last commit message to interceptor response for BitBucket

---

sonar-project.properties

chore: Update sonar scanner config (#311)

---

CHANGELOG.md

This change updates the CHANGELOG.md file

docs: Update changelog file for release notes (#302)

---

charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible.yaml

Added resources for deploying RPM packages using Ansible in the Tekton Pipeline.
- Added a `Pipeline` for deploying RPM packages with Ansible.
- Included tasks for pre-deployment, deployment, and post-deployment of applications.
- Used a Python script to clone the Git repository and execute Ansible playbooks.
- Added necessary parameters to pass application payload, pipeline name, and stage information.
Tested across all stages of the Pipeline, including:
- Verifying Git repository cloning.
- Executing Ansible playbooks for each application in the payload.
- Running the Ansible command to deploy packages.

feat: Add resources for deploy rpm(#275)

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_bitbucket.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/pipelines/go/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/go/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/go/bitbucket-review.yaml
charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-build.yaml
charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-review.yaml
charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml

feat: Add support Bitbucket VSC for Go pipelines

---

pkg/event_processor/bitbucket/bitbucket.go

Use basic auth for Bitbucket API requests.
Fixes #311 
- Manual testing

fix: Use basic auth for Bitbucket Api request

---

charts/pipelines-library/templates/tasks/bitbucket-set-status.yaml

chore: Update auth type for set-status task

---

charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml

Point to correct pipeline
Fixes: #329
run on env
N/A

fix: Fix TriggerTemplate for deploy-with-approval flow (#329)

---

charts/pipelines-library/templates/tasks/check-helm-chart-name.yaml
charts/pipelines-library/templates/tasks/codenarc.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/GetVersion.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberDotnet.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberGradle.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberPython.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberCsharp.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberDotnet.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberGradle.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberHelmChart.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberPython.yaml
charts/pipelines-library/templates/tasks/kaniko.yaml
charts/pipelines-library/templates/tasks/maven-get-module.yaml
tests/e2e/bitbucket/01-assert.yaml
tests/e2e/bitbucket/01-install.yaml
tests/e2e/gerrit/01-assert.yaml
tests/e2e/gerrit/01-install.yaml
tests/e2e/github/01-assert.yaml
tests/e2e/github/01-install.yaml
tests/e2e/gitlab/01-assert.yaml
tests/e2e/gitlab/01-install.yaml

Update alpine base image to v3.18.9
Fixes #331

chore: Update alpine base image to v3.18.9 (#331)

---

charts/pipelines-library/templates/pipelines/python/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/python/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/python/github-build-default.yaml
charts/pipelines-library/templates/pipelines/python/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/github-review.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/python/gitlab-review.yaml

fix: Update image for python pipelines

---

charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml

Pass env vars from ConfigMap for deploy-applicationset-cli task
Fixes #307 

feat: Pass env vars from ConfigMap for deploy task (#307)

---

charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-build.yaml
charts/pipelines-library/templates/triggers/bitbucket/triggerbinding-review.yaml

fix: Fix git link for the bitbucket TriggerBinding (#336)

---

charts/pipelines-library/templates/tasks/push-to-jira.yaml

Fix BitBucket commit url for Jira integration
Fixes #317

fix: Fix BitBucket commit url for Jira integration (#317)

---

charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Align tekton-cache version (#341)

---

CHANGELOG.md
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#341)

---

charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/infrastructure/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/infrastructure/github-build-default.yaml
charts/pipelines-library/templates/pipelines/infrastructure/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/infrastructure/github-review.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/infrastructure/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/terraform/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/terraform/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/terraform/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/terraform/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/terraform/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/terraform/gerrit-review-lib.yaml
charts/pipelines-library/templates/pipelines/terraform/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/terraform/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/terraform/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/terraform/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/terraform/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/terraform/gitlab-review-lib.yaml
charts/pipelines-library/templates/tasks/terraform-check.yaml

chore: Update default terraform version to 1.5.7 (#345)

---

pull_request_template.md

Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #56

chore: Update Pull Request Template (#56)

---

charts/pipelines-library/templates/tasks/helm-libraries/helm-lint-lib.yaml

fix: Set correct repository for chart-testing task (#348)

---

charts/pipelines-library/templates/tasks/get-cache.yaml

chore: Increase resources for get-cache task (#348)

---

charts/pipelines-library/templates/tasks/git-cli.yaml
charts/pipelines-library/templates/tasks/kaniko.yaml
charts/pipelines-library/templates/tasks/send-to-microsoft-teams.yaml

chore: Set correct image tag for kaniko task (#348)

---

charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-general.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml

fix: Add handler to check sonar availability

---

charts/pipelines-library/templates/pipelines/python/flask/github-build-default.yaml
charts/pipelines-library/templates/pipelines/python/flask/github-review.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/wait-autotest.yaml
charts/pipelines-library/templates/tasks/autotests/TestsMavenAutotest.yaml
charts/pipelines-library/templates/tasks/bitbucket-set-status.yaml
charts/pipelines-library/templates/tasks/commit-validate.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberNpm.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/GetVersionEDP.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberNpm.yaml
charts/pipelines-library/templates/tasks/github-set-status.yaml
charts/pipelines-library/templates/tasks/helm-docs.yaml
charts/pipelines-library/templates/tasks/helm-libraries/helm-docs-lib.yaml
charts/pipelines-library/templates/tasks/init-values.yaml
charts/pipelines-library/templates/tasks/opa.yaml
charts/pipelines-library/templates/tasks/push-to-jira.yaml
charts/pipelines-library/templates/tasks/send-to-microsoft-teams.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-general.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
charts/pipelines-library/templates/tasks/update-cbb.yaml
charts/pipelines-library/templates/tasks/update-cbis.yaml
hack/images/images.txt
hack/images/update_image_list.py

chore: Standardize Tekton Agents Image Versions

---

charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml

Fix NaN sync error in deployment process.
Fixes #363

fix: Fix NaN sync error in deployment process (#363)

---

charts/pipelines-library/templates/tasks/cd/clean.yaml
charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml
charts/pipelines-library/templates/tasks/promote-images.yaml
hack/images/images.txt

Updated the tekton-cd-pipeline image version to include the latest version of the Argo CD CLI.
Fixes #373

chore: Update tekton-cd-pipeline image version (#373)

---

charts/pipelines-library/templates/_helpers.tpl

The Sonar task should execute successfully using the correct base image, allowing the pipeline to continue to subsequent tasks without errors.
Deployed on dev environment.

fix: Align resourceMapping for gradle sonar(#375)

---

charts/tekton-cache/Chart.yaml
charts/tekton-cache/README.md

chore: Bumo tekton-cache version (#379)

---

charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Bump tekton-cache version (#379)

---

CHANGELOG.md
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#379)

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_github.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

fix: Disable github voting for null sha (#385)

---

charts/pipelines-library/Chart.lock
charts/pipelines-library/templates/resources/cm-gradle-settings.yaml
charts/pipelines-library/templates/resources/cm-maven-settings.yaml
charts/pipelines-library/templates/resources/cm-npm-settings.yaml
charts/pipelines-library/templates/resources/cm-nuget-settings.yaml
charts/pipelines-library/templates/resources/cm-python-settings.yaml

chore: Update Naming Convention for Nexus-Operator Resources

---

go.mod
go.sum

Update dependencies
Fixes #389 

chore(deps): Bump golang.org/x/net to v.0.33.0

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_bitbucket.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/pipelines/docker/kaniko/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/opa/bitbucket-review-lib.yaml

fix: Update bitbucket vote parameters

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_bitbucket.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/maven/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/maven/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-edp.yaml

fix: Update bitbucket set-status task condition

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/triggers/bitbucket/tt-build.yaml
charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml
charts/pipelines-library/templates/triggers/cd/clean.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/triggers/cd/deploy.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
charts/pipelines-library/templates/triggers/github/tt-build.yaml
charts/pipelines-library/templates/triggers/github/tt-review.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml
charts/pipelines-library/values.yaml

feat: Enable node selector for tekton pipelines

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common_gitlab.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/maven/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/maven/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-build-lib-edp.yaml

fix: Update gitlab set-status task condition

---

CHANGELOG.md
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#400)

---

charts/pipelines-library/templates/resources/cm-gradle-settings.yaml

fix: Update Naming Convention for gradle cm

---

charts/common-library/templates/_common_bitbucket.yaml
charts/pipelines-library/templates/pipelines/docker/kaniko/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/opa/bitbucket-review-lib.yaml

fix: Fix pipeline status report (#385)

---

charts/pipelines-library/templates/triggers/bitbucket/tt-build.yaml
charts/pipelines-library/templates/triggers/bitbucket/tt-review.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
charts/pipelines-library/templates/triggers/github/tt-build.yaml
charts/pipelines-library/templates/triggers/github/tt-review.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml

chore: Align pipelineRun name patterns

---

charts/pipelines-library/templates/pipelines/_common_dotnet.yaml
charts/pipelines-library/templates/pipelines/csharp/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/csharp/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/csharp/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/csharp/github-review.yaml
charts/pipelines-library/templates/pipelines/csharp/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/csharp/gitlab-review.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
hack/images/images.txt

Bump dotnet sonar image version for report push after bump SonarQube version to 9.9.7.
Deployed on develop an environment

chore: Bump dotnet sonar image version for report push(#411)

---

charts/pipelines-library/templates/pipelines/docker/kaniko/github-review.yaml
charts/pipelines-library/templates/pipelines/docker/kaniko/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm-pipelines/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/github-review.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-review-lib.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/github-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/opa/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/opa/gitlab-review-lib.yaml

fix: Update voting tasks

---

charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/pipelines/cd/deploy.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml

feat: Add APPLICATIONS_PAYLOAD results to deploy tasks

---

charts/pipelines-library/templates/resources/gitservers/quicklink.yaml
charts/pipelines-library/tests/test_baseline.py
charts/pipelines-library/tests/test_bitbucket_integration.py
charts/pipelines-library/tests/test_gerrit_integration.py
charts/pipelines-library/tests/test_github_integration.py
charts/pipelines-library/tests/test_gitlab_integration.py
charts/pipelines-library/values.yaml
tests/e2e/values.yaml

Make QuickLink installation resources optional
Fixes #409

chore: Make QuickLink installation optional (#409)

---

charts/pipelines-library/templates/pipelines/gitops/bitbucket-build.yaml
charts/pipelines-library/templates/pipelines/gitops/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/gitops/gerrit-build.yaml
charts/pipelines-library/templates/pipelines/gitops/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/gitops/github-build.yaml
charts/pipelines-library/templates/pipelines/gitops/github-review.yaml
charts/pipelines-library/templates/pipelines/gitops/gitlab-build.yaml
charts/pipelines-library/templates/pipelines/gitops/gitlab-review.yaml

chore: Rename parameter edp-gitops to krci-gitops

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#419)

---

charts/pipelines-library/templates/pipelines/cd/deploy-diff-approve.yaml
charts/pipelines-library/templates/tasks/cd/sync-app.yaml
charts/pipelines-library/templates/triggers/cd/deploy-diff-approve.yaml

feat: Enhance Deployment Pipeline for Approval Process

---

charts/pipelines-library/templates/tasks/kaniko.yaml

fix: Fix kaniko execution for registry with custom certificates (#427)

---

charts/pipelines-library/templates/tasks/security.yaml
hack/images/images.txt

Update security task images (semgrep & cdxgen)
Fixes #429

chore: Update security task images (#429)

---

charts/pipelines-library/templates/tasks/image-scan.yaml
charts/pipelines-library/templates/tasks/security.yaml
hack/images/images.txt

Upgrade Image Scan Task (update Tool Versions, remove Report Portal Integration, and add DefectDojo Integration)
Fixes #431

chore: Upgrade image-scan Task (#431)

---

charts/pipelines-library/templates/pipelines/security/image-scan-remote.yaml
charts/pipelines-library/templates/tasks/image-scan-remote.yaml

Add image-scan task for remote registries (ECR, Harbor, Nexus etc.)
Fixes #433

chore: Add image-scan task for remote registries (#433)

---

charts/common-library/templates/_common.yaml
charts/pipelines-library/templates/tasks/security.yaml
hack/images/images.txt

Integrate Gitleaks for secret scanning (with DefectDojo integration)
Fixes #435

chore: Integrate Gitleaks for secret scanning (#435)

---

charts/pipelines-library/templates/pipelines/go/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/go/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/go/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/go/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/go/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/go/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/go/github-build-default.yaml
charts/pipelines-library/templates/pipelines/go/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/go/github-review.yaml
charts/pipelines-library/templates/pipelines/go/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/go/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/go/gitlab-review.yaml
charts/pipelines-library/templates/tasks/go.yaml
hack/images/images.txt

Update Go image version to 1.24
Fixes #444 

chore: Update Go image version to 1.24

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/resources/serviceaccount-tekton.yaml
charts/pipelines-library/values.yaml

Add `imagePullSecrets` field to Tekton ServiceAccount.
Fixes #442

chore: Add imagePullSecrets field to Tekton ServiceAccount (#442)

---

hack/images/migrate_ecr.py
hack/images/migrate_nexus.py

feat: Create migration script for Nexus registry integration

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#452)

---

charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/wait-autotest.yaml
charts/pipelines-library/templates/tasks/get-cache.yaml
charts/pipelines-library/templates/tasks/gitops/yaml-lint.yaml
charts/pipelines-library/templates/tasks/push-to-jira.yaml
charts/pipelines-library/templates/tasks/save-cache.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-dotnet.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-general.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-maven.yaml
hack/images/images.txt

Allow custom yamllint configuration in GitOps pipelines by using a `.yamllint` file
Fixes #450 

chore: Allow custom yamllint configuration in GitOps pipelines (#450)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/resources/pruner/cron-job.yaml
charts/pipelines-library/values.yaml

Add ImagePullSecrets field support in the Helm chart
Fixes #455

chore: Add ImagePullSecrets field support (#455)

---

charts/pipelines-library/templates/tasks/ecr-to-docker.yaml

Update crane/debug image tag version.
Fixes #455

chore: Update crane image tag version (#455)

---

charts/pipelines-library/templates/tasks/create-ecr-repository.yaml
charts/pipelines-library/templates/tasks/ecr-to-docker.yaml
charts/pipelines-library/templates/tasks/helm-libraries/helm-push-lib.yaml
charts/pipelines-library/templates/tasks/helm-push.yaml
charts/pipelines-library/templates/tasks/init-values.yaml
charts/pipelines-library/templates/tasks/kaniko-dockerbuild-verify.yaml
charts/pipelines-library/templates/tasks/kaniko.yaml

chore: Rename ConfigMap from 'edp-config' to 'krci-config'

---

CHANGELOG.md

chore: Update current development version (#462)

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md

chore: Update current development version (#468)

---

charts/pipelines-library/templates/pipelines/security/security-scan-bitbucket.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gerrit.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-github.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gitlab.yaml

chore: Enable security pipeline expressions (#464)

---

charts/pipelines-library/templates/tasks/update-cbis.yaml

Update codebasebranch label to improve consistency
Fixes #472 
- Unit test

refactor: Update codebasebranch label to improve consistency

---

charts/pipelines-library/templates/tasks/image-scan-remote.yaml
charts/pipelines-library/templates/tasks/image-scan.yaml
charts/pipelines-library/templates/tasks/opa.yaml
charts/pipelines-library/templates/tasks/send-to-microsoft-teams.yaml
hack/images/images.txt

Update base image versions in configuration files
Fixes #433

chore: Update base image versions

---

charts/pipelines-library/templates/pipelines/security/image-scan-remote.yaml
charts/pipelines-library/templates/tasks/image-scan-remote.yaml
charts/pipelines-library/templates/triggers/security/tt-image-scan-remote.yaml

- Added `TriggerTemplate` resource for `image-scan-remote` pipeline
- Fixed `grype` step if `CONTAINER_REGISTRY_TYPE` = `ecr`
Fixes #489

chore: Add TriggerTemplate for image-scan-remote pipeline

---

charts/pipelines-library/templates/pipelines/security/security-scan-bitbucket.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gerrit.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-github.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gitlab.yaml
charts/pipelines-library/templates/triggers/bitbucket/tt-security.yaml
charts/pipelines-library/templates/triggers/cd/clean.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible.yaml
charts/pipelines-library/templates/triggers/cd/deploy-diff-approve.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/triggers/cd/deploy.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-security.yaml
charts/pipelines-library/templates/triggers/github/tt-security.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-security.yaml

chore: Define correct TriggerTemplate labels (#491)

---

charts/pipelines-library/templates/pipelines/security/image-scan-remote.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-bitbucket.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gerrit.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-github.yaml
charts/pipelines-library/templates/pipelines/security/security-scan-gitlab.yaml
charts/pipelines-library/templates/tasks/image-scan-remote.yaml

- Added DefectDojo result link for `image-scan-remote` pipeline.
- Updated the description fields for all security-related Tekton pipelines.
Fixes #494

chore: Add DefectDojo result link

---

charts/pipelines-library/templates/triggers/bitbucket/tt-autotests.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-autotests.yaml
charts/pipelines-library/templates/triggers/github/tt-autotests.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-autotests.yaml
charts/pipelines-library/templates/triggers/security/tt-image-scan-remote.yaml

Align `podTemplate` usage for `TriggerTemplate` resources.
Fixes #498

chore: Align podTemplate usage for TriggerTemplate

---

charts/pipelines-library/templates/pipelines/cd/clean.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-diff-approve.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/pipelines/cd/deploy.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
charts/pipelines-library/templates/tasks/cd/clean.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
charts/pipelines-library/templates/tasks/cd/deploy-applicationset-cli.yaml
charts/pipelines-library/templates/tasks/cd/run-quality-gate.yaml
charts/pipelines-library/templates/tasks/cd/run-сleanup-gate.yaml
charts/pipelines-library/templates/tasks/cd/sync-app.yaml
charts/pipelines-library/templates/tasks/promote-images.yaml

Refactor deprecated parameters (`PIPELINE`,`STAGE`) for CD pipelines.
Fixes #503

chore: Refactor deprecated parameters for CD pipelines

---

charts/common-library/templates/_common.yaml
charts/pipelines-library/templates/tasks/update-cbb.yaml

Align update-cbb task trigger condition.
Fixes #509

chore: Align update-cbb task trigger condition

---

charts/tekton-cache/README.md
charts/tekton-cache/templates/deployment.yaml
charts/tekton-cache/values.yaml

chore: Replace deprecated tekton-cache image

---

charts/pipelines-library/templates/tasks/git-clone.yaml
kuttl-test.yaml

Replace deprecated `git-init` image.
Fixes #511

chore: Replace deprecated git-init image

---

pkg/event_processor/bitbucket/bitbucket.go
pkg/event_processor/event.go
pkg/event_processor/event_test.go
pkg/event_processor/github/github.go
pkg/event_processor/gitlab/gitlab.go

Fix Gerrit pipeline triggering.
Fixes #515 
- unit tests
- manually

fix: Retrigger pipeline for the Gerrit not working

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/tekton-cache/Chart.yaml
charts/tekton-cache/README.md

chore: Update current development version (#517)

---

charts/pipelines-library/templates/pipelines/go/gitlab-review.yaml

Fix invalid `image` parameter in `Go` review pipelines.
Fixes #523

fix: Fix invalid image parameter in Go review pipelines (#523)

---

charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-review.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-review-lib.yaml

fix: Update nexus path for components

---

charts/pipelines-library/templates/pipelines/_common_dotnet.yaml

Update dotnet artefact push command for Nexus `v0.18.0+` compatibility
Fixes #529

chore: Update dotnet artifact push command

---

charts/pipelines-library/templates/triggers/gitlab/triggerbinding-build.yaml

fix: Update Gitlab gitrevision parameter

---

CHANGELOG.md

chore: Update current development version (#545)
