epam/edp-tekton

charts/pipelines-library/scripts/tekton-prune.sh
charts/pipelines-library/templates/resources/pruner/cron-job.yaml
charts/pipelines-library/templates/resources/pruner/rbac.yaml
charts/pipelines-library/templates/resources/pruner/secret.yaml
charts/pipelines-library/values.yaml

The change replaces removal of the whole PipelineRun and all of it's resources with removal of only Pods and PVCs.
This allows preserving history of PipelineRuns in Tekton Dashboard.
Also this enables automated removal of workspace volumes, for example EBS Volumes in AWS when AWS EBS CSI Controller is used.
- Chart linting performed with `helm lint`.
- The `pipelines-library` helm chart was checked with Chart Testing `ct lint`.
- All the `tekton-resource-pruner`-related templates of the  `pipelines-library` helm chart were rendered with this `helm template` command:
```sh
helm template tekton-resource-pruner -n $namespace \
./charts/pipelines-library -s templates/resources/pruner/* > /tmp/tekton-resource-pruner.yaml
```
- The rendered templates were deployed to a Kubernetes cluster:
```sh …
```

Re-design Tekton Resource Pruner to delete only Pods and PVCs

---

charts/custom-pipelines/templates/cd/deploy-custom.yaml
charts/pipelines-library/templates/triggers/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/triggers/cd/deploy.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-build.yaml
charts/pipelines-library/templates/triggers/gerrit/tt-review.yaml
charts/pipelines-library/templates/triggers/github/tt-build.yaml
charts/pipelines-library/templates/triggers/github/tt-review.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-build.yaml
charts/pipelines-library/templates/triggers/gitlab/tt-review.yaml

Description
This patch introduces an enhancement that excludes the display of PipelineRun resources in the ArgoCD interface. The main purpose of this change is to prevent clutter and confusion caused by extraneous diff output, making the ArgoCD UI more streamlined and focused on relevant resources. This is achieved by adding a specific annotation (argocd.argoproj.io/compare-options: IgnoreExtraneous) to the PipelineRun resources within various templates.
Fixes #169
Type of change
The change has been tested by deploying the modified templates and confirming that the PipelineRun resources no longer appear in the ArgoCD resources UI. Automated tests were also run to ensure existing functionality remains unaffected.
Checklist:

feat: Exclude pipelinerun from resources displayed in argocd(#169)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/resources/cm-gradle-settings.yaml
charts/pipelines-library/templates/tasks/edp-gradle.yaml
charts/pipelines-library/templates/tasks/gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
charts/pipelines-library/values.yaml

- Enable conditional environment variable injection in Gradle tasks through `.Values.tekton.packageRegistriesSecret.enabled`.
- Add `gradleConfigMap: "custom-gradle-settings"` to `tekton` configs, allowing for custom Gradle settings that facilitate access to artifact storages as proxies.
- Refactor `custom-gradle-settings` ConfigMap with an updated `init.gradle` script. It dynamically configures credentials for Nexus, GitLab, GitHub, and Azure DevOps, ensuring secure and flexible integration.

feat: Enhance Gradle proxy support (#132)

---

charts/pipelines-library/templates/resources/route-eventlistener.yaml

Description
This change addresses the issue where the EDP-Tekton pipeline library was creating only a single eventListener route resource on OpenShift, regardless of the number of git servers configured with eventListener ingress enabled. The fix involves modifying the Helm chart template to iterate over the gitServers values and create a unique OpenShift Route for each eligible git server. This ensures that each eventListener has its own route for proper functionality and accessibility.
Fixes # (issue reference not provided, please include if available)
Type of change
The changes have been tested by deploying the updated Helm chart to an OpenShift cluster and verifying that a Route is successfully created for each git server with eventListener ingress enabled. …

fix: multiple eventListeners route creation

---

charts/pipelines-library/templates/pipelines/_common_java_gradle.yaml
charts/pipelines-library/templates/resources/cm-gradle-settings.yaml
charts/pipelines-library/templates/tasks/edp-gradle.yaml
charts/pipelines-library/templates/tasks/gradle.yaml

This PR aims to dynamically set repository URLs for package types. It introduces changes that remove explicit Nexus credentials (`nexusLogin`, `nexusPassword`, and `nexusMavenRepositoryUrl`) from Gradle command lines in build, test, and compile tasks. Moreover, it incorporates `SNAPSHOTS_REPO_PATH` and `RELEASES_REPO_PATH` into the `custom-gradle-settings` ConfigMap, allowing for dynamic configuration of repository URLs based on the build context. A `configMapKeyRef` has been added to the Gradle task to enable dynamic retrieval of Nexus URL, snapshots, and releases repository paths from the Kubernetes ConfigMap.
Fixes #132
The description does not provide specific details on tests. It's recommended to describe the tests that were conducted to ensure the changes are effective and provide …

feat: Dynamically set repository URLs for package types (#132)

---

charts/pipelines-library/README.md
charts/pipelines-library/templates/dashboard/deployment.yaml
charts/pipelines-library/values.yaml

Description
This pull request updates the Tekton dashboard version to v0.46.0 and aligns the pod arguments to use --namespaces instead of the previously incorrect --namespace. This change ensures that the Tekton pipeline library is using the current application version of the Tekton dashboard, adhering to the acceptance criteria of keeping the application up-to-date and ensuring the arguments are correctly specified according to the latest specifications.
Type of change
- [х] New feature (non-breaking change which adds functionality)
The changes were tested in a development environment where the Tekton dashboard deployment was successfully updated to version v0.46.0, and the pods were correctly picking up the --namespaces argument, ensuring that the dashboard …

chore: Update tekton-dashboard(#180)

---

charts/pipelines-library/templates/tasks/helm-libraries/helm-push-lib.yaml
charts/pipelines-library/templates/tasks/helm-push.yaml

Description
This PR introduces two minor but essential changes to the Helm push tasks for both Helm applications and libraries. Specifically, it adds an optional aws_region parameter to the tasks, allowing for more flexible configuration when dealing with different AWS regions. This enhancement ensures that our Helm push operations are more adaptable to various deployment environments, particularly when interacting with AWS services.
Type of change
The changes were tested by deploying Helm charts to different AWS regions, ensuring that the aws_region parameter is correctly utilized and that the Helm push operations succeed without any issues. The tests were conducted in a development environment with configurations mimicking those of our production settings to …

fix: Make possible work with registry without registry parameter(#184)

---

charts/pipelines-library/templates/tasks/hadolint.yaml

In this update, I changed the Docker linter image from ghcr.io/hadolint/hadolint:v2.8.0-debian to ghcr.io/hadolint/hadolint:v2.12.0-alpine. This change was necessary for several reasons: the Alpine version of the image is smaller and more secure due to fewer included packages, which aligns with our goal to optimize our CI/CD pipeline for speed and security. Additionally, the update to version 2.12.0 brings in new linting rules and bug fixes that improve the quality of our Dockerfile linting process. I also removed the #!/bin/bash shebang from the script as it was redundant. This script is intended to be run in environments where bash is the default shell, and its presence could cause issues in environments where bash is not available or not the default.
Fixes #188 
I tested the update by …

chore: Bump hadolint version to v2.12.0-alpine (#188)

---

.github/workflows/e2e.yaml

For push to master e2e workflow Go version is missing.
Workfllow can fail if if takes Go version not equal 1.22.
Fixes #182

chore: Use Go 1.22 for e2e workflow

---

charts/pipelines-library/templates/triggers/github/trigger-review.yaml

This pull request removes the trigger for pipelines when a pull request is modified. The intention is to reduce unnecessary pipeline runs when minor edits are made to a PR. This change requires users to manually retrigger the review pipeline by commenting /recheck or by pushing new changes to the PR.
Fixes #187
Tested by making edits to existing PRs and observing that the pipeline was not triggered. Additionally, the /recheck command and pushing new commits were tested to confirm they correctly trigger the pipeline.
This change aims to optimize the use of CI resources by preventing unnecessary pipeline runs, thus saving time and compute resources.

chore: Remove PR modify action for review pipeline (#187)

---

charts/pipelines-library/templates/resources/gitservers/eventlistener.yaml
charts/pipelines-library/templates/resources/gitservers/ingress-eventlistener.yaml
charts/pipelines-library/templates/resources/route-eventlistener.yaml
charts/pipelines-library/tests/test_baseline.py
charts/pipelines-library/tests/test_github_integration.py
tests/e2e/gerrit/02-assert.yaml
tests/e2e/github/02-assert.yaml
tests/e2e/gitlab/02-assert.yaml

This reverts commit df13f9650445e9263b1186963bc4ae8f02e48b25.
We need to keep old naming schema for better user experience
Fixes #222

chore: Revert Update gitservers event listener name and add label (#222)

---

pkg/event_processor/event.go
pkg/event_processor/gerrit/gerrit_test.go
pkg/event_processor/gitlab/gitlab_test.go
pkg/github/github_test.go
pkg/interceptor/edp_interceptor.go

Make it possible to re-trigger the Tekton pipeline using the "/ok-to-test" comment in pull requests. This feature will enhance the flexibility of pipeline executions by allowing developers to manually trigger the pipeline as needed when GitHub owners are enabled. This feature is equal to /recheck
Fixes #238 
Unit tests.

feat: Re-trigger Tekton Pipeline with /ok-to-test comment

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/tasks/push-to-jira.yaml

This pull request updates the configuration and script files to replace the usage of `PIPELINE_URL` with `GIT_WEB_URL`. The changes include:
- Removing `PIPELINE_URL` from the environment variables and YAML configurations.
- Updating the script to use `GIT_WEB_URL` instead of `PIPELINE_URL` for generating the issue link.
This change ensures that the Jira issue link now correctly uses the Git commit URL instead of the pipeline URL, aligning with the project requirements.
I tested the changes by running the Tekton task with the updated configuration and verified that the Jira issue link was correctly generated using the `GIT_WEB_URL` and included the commit ID.

feat: Update jira task Include GitCommit instead of Pipeline URL(#252)

---

charts/pipelines-library/templates/pipelines/java/maven/github-rpm-build-default.yaml
charts/pipelines-library/templates/pipelines/java/maven/github-rpm-build-edp.yaml
charts/pipelines-library/templates/tasks/edp-rpm.yaml

This Pull Request introduces a new feature to implement a review and build pipeline that supports RPM for Java and Maven across all Java versions. The necessity for such a feature was identified in the related GitHub issue and aims to streamline the development process by offering better integration with various Git servers.
Related issue #282 
The changes have been tested by creating a mock project that utilizes the new pipeline capabilities.
- Automated tests were added to validate the pipeline's functionality with different Java versions.
- Manual tests were conducted on GitLab, GitHub, and Gerrit to ensure seamless integration.
The development of this feature was guided by the need to support a more diverse set of technologies and platforms within our build and review pipelines, as …

chore: Update rpm-build flow for java17 maven (#282)

---

charts/pipelines-library/templates/triggers/cd/deploy-with-approve.yaml

Fix Tekton TriggerTemplate for deploy pipeline with approval step. This change is needed to ensure that the deploy pipeline with approval step functions as expected.
Related issue #279
I have tested this fix by running the deploy pipeline with the approval step and verifying that the approval step functions correctly. Detailed testing instructions are provided in the pull request.
No additional context is necessary for this feature request.

fix: Fix TriggerTemplate for deploy with approve step (#279)

---

hack/validate_tekton.py

We don't need to define specific configuration file, since options are simple, so let's keep script simple

chore: Remove config.yaml from validation script (#290)

---

charts/pipelines-library/templates/resources/gitservers/quicklink.yaml
charts/pipelines-library/tests/test_gerrit_integration.py
charts/pipelines-library/tests/test_github_integration.py
charts/pipelines-library/tests/test_gitlab_integration.py

Validated the `type` field for QuickLink resources for gitServers
Fixes #304

chore: Validate 'type' field for QuickLink resources (#304)

---

.github/workflows/e2e.yaml
.github/workflows/pr.yaml
kuttl-test.yaml
sonar-project.properties

Keep 1.30 version of kubernetes
Set production used version of Tekton

chore: Update e2e tests for GH, switch to stable version of Tekton

---

charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/triggers/cd/deploy-ansible-awx.yaml

Add Tekton task, pipeline and trigger template for deploy RPM package via tower-cli.
Fixes #277 

feat: Add Tekton resources for deploy RPM package via AWX (#277)

---

charts/common-library/Chart.yaml
charts/common-library/README.md
charts/common-library/templates/_common.yaml
charts/pipelines-library/Chart.lock
charts/pipelines-library/Chart.yaml
charts/pipelines-library/README.md
charts/pipelines-library/templates/pipelines/rpm/maven/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/rpm/maven/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/rpm/maven/github-build-default.yaml
charts/pipelines-library/templates/pipelines/rpm/maven/gitlab-build-default.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
charts/pipelines-library/templates/tasks/edp-rpm.yaml
charts/pipelines-library/templates/tasks/getversion/defaulttype/GetVersionRPM.yaml

fix: Update rpm default versioning

---

charts/pipelines-library/templates/pipelines/cd/clean.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/tasks/run-сleanup-gate.yaml
charts/pipelines-library/templates/triggers/cd/clean.yaml

This PR introduces a new cleanup task in the CD pipeline, enhancing the pipeline with pre- and post-cleanup stages. It includes additional parameters for secret configuration and extra commands, which facilitate more customizable cleanup operations across environments. Documentation and code comments have been added for clarity.
The new task has been tested in a developer-stage environment. The application was deployed successfully and cleaned up using the updated pipeline. Verified pipeline behavior and successful cleanup in different test scenarios.

feat: Add support kubeconfig in clean pipeline(#350)

---

charts/pipelines-library/templates/triggers/gitlab/trigger-review.yaml

Disable GitLab trigger on reviewer/assignee changes
Fixes #358

chore: Disable GitLab trigger on reviewer change (#358)

---

charts/pipelines-library/templates/pipelines/cd-autotests/autotest.yaml
charts/pipelines-library/templates/pipelines/cd/clean.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-ansible.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-approve.yaml
charts/pipelines-library/templates/pipelines/cd/deploy-with-autotests.yaml
charts/pipelines-library/templates/pipelines/cd/deploy.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/run-autotests-java.yaml
charts/pipelines-library/templates/tasks/cd/clean.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible-awx.yaml
charts/pipelines-library/templates/tasks/cd/deploy-ansible.yaml
charts/pipelines-library/templates/tasks/cd/run-quality-gate.yaml
charts/pipelines-library/templates/tasks/cd/run-сleanup-gate.yaml

This enhancement allows all stages in the CD pipeline to access and use custom variables defined within their stage configurations, ensuring consistency across the pipeline. Additionally, autotest stages can now leverage these custom variables from their corresponding stage configurations, improving flexibility and customization in testing.
This change was deployed in a development environment where the CD pipelines and all associated stages were executed. Each stage was verified to confirm it could access and use the specified custom variables as intended.

chore: Enable deployment env variables in CD pipelines(#360)

---

charts/pipelines-library/templates/tasks/getversion/defaulttype/UpdateBuildNumberGradle.yaml
charts/pipelines-library/templates/tasks/getversion/edptype/UpdateBuildNumberGradle.yaml

Description
This Pull Request updates the logic in the UpdateBuildNumberGradle task within the edp-tekton project. The update modifies the versioning logic based on the IS_RELEASE_BRANCH flag.
Type of change
Testing was performed to ensure that the updated logic works as intended.
Verified that the versioning updates are applied correctly for both release and non-release branches.
No regressions or unexpected behaviors were observed during testing.
Deploy the updated task to a test environment.
Confirm that the versioning is updated correctly in each case.
Checklist:

chore: Align quotation marks regex patterns gradle(#370)

---

charts/pipelines-library/templates/_helpers.tpl
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/github-review-lib.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-review-lib.yaml
charts/pipelines-library/templates/tasks/autotest-cd-pipeline/init-autotests.yaml
charts/pipelines-library/templates/tasks/codenarc.yaml
charts/pipelines-library/templates/tasks/edp-gradle.yaml
charts/pipelines-library/templates/tasks/gradle.yaml
charts/pipelines-library/templates/tasks/sonar/sonarqube-gradle.yaml
hack/images/images.txt

All references to the Gradle image in the edp-tekton project have been updated to version gradle:7.6.1-jdk17.
The functionality of the project was tested in a test environment to ensure operability after the update.
Issues related to the new image version, if any, were identified and resolved.
Type of change
Testing was performed on a test environment.
Verified that all project functions work correctly with the updated Gradle image (gradle:7.6.1-jdkXX).
Ensured no regressions or new issues were introduced by the update.
Deploy the updated resources to the test environment.
Test the main functions of the project.
Validate that the project operates as expected with no errors.
Checklist:

chore: Bump gradle image version(#369)

---

charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/github-review.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/autotests/gradle/gitlab-review.yaml

While executing the Sonar step in Java AUTs (gerrit-gradle-java8-aut, gerrit-gradle-java11-aut, gerrit-gradle-java17-aut), the following error was encountered: '/tekton/scripts/script-1-wljth: line 5: gradle: command not found'. This indicates that the Gradle command is not available in the environment where the script is executed.
On dev environment.

fix: Sonar image name resource mapping in pipelines(#375)

---

charts/pipelines-library/templates/pipelines/js/npm/gitlab-build-edp.yaml

During the execution of pipelines for GitLab Git provider, it has been identified that extra symbols within the BaseImage value are causing failures in pulling the TaskRunImage into the pipeline. This issue obstructs the pipeline's ability to proceed with tasks that rely on the TaskRunImage, thereby impacting the efficiency and success rate of the pipeline executions.
Acceptance Criteria:
1. The BaseImage value should not contain any extra, non-essential symbols that could interfere with the parsing or execution processes.
2. The pipeline should successfully pull the TaskRunImage without errors related to the BaseImage value.
3. Pipeline executions involving the TaskRunImage should proceed as expected without being hindered by issues related to the BaseImage value.
4. A verification …

fix: Align resource mapping(#375)

---

charts/common-library/templates/_common.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/bitbucket-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gerrit-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/github-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-default.yaml
charts/pipelines-library/templates/pipelines/groovy/gitlab-build-lib-edp.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/helm/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/helm/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/helm/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/helm/github-build-default.yaml
charts/pipelines-library/templates/pipelines/helm/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/helm/gitlab-build-edp.yaml
charts/pipelines-library/templates/tasks/init-values.yaml
charts/pipelines-library/templates/tasks/update-cbis.yaml

This change is due to reworking relation between CodebaseBranch and CodebaseImageStream.
epam/edp-codebase-operator#198
The CodebaseImageStream now has a label that allows it to select CodebaseBranch.
Fixes #472
- Manual testing

feat: Use label selector for CodebaseImageStream

---

charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-build-default.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-build-edp.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/bitbucket-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-build-default.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-build-edp.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gerrit-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/github-build-default.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/github-build-edp.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/github-review.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-build-default.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-build-edp.yaml
charts/pipelines-library/templates/pipelines/js/npm/antora/gitlab-review.yaml
charts/pipelines-library/templates/tasks/edp-npm.yaml

Description
This PR addresses an issue where the npm cache was not being reused properly during dependency resolution. As a result, redundant downloads occurred on each build, leading to excessively large cache archives that could not be unpacked.
To resolve this, we added a cache verification step using:
bash
```
npm cache verify --cache $NPM_CACHE_DIR
```
This ensures the cache is valid and allows npm to reuse it reliably across builds.
Fixes #734
Type of change
The change has been tested in the CI/CD pipeline where multiple builds were executed using the same cache directory. After adding the npm cache verify step, the cache is consistently reused across builds, and no excessive growth or unpacking failures occur.
To reproduce:
Set up a pipeline using a shared …

chore: Npm cache reuses instead of downloading dependencies again

---

charts/pipelines-library/templates/tasks/image-scan-remote.yaml

Make `aws_region` configMapKeyRef optional in `image-scan-remote` pipeline.
Fixes #489

chore: Make aws_region configMapKeyRef optional (#489)
